version: '3'
services:
  app:
    image: node:latest
    container_name: "node-app"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    command: npm start
    ports:
      - 3100:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin123"
      DB_DATABASE: "irri-db"
    links:
      - db
  db:
    image: "mysql:5.7.24"
    container_name: "typeorm-mysql"
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "irri-db"
    restart: always
    logging:
      driver: 'json-file'
      options:
        "max-size": "1G"
